In [11]:
import numpy as np
#a=[1,2,3,4,24,4,3,4]
arr=np.arange(1,23)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [13]:
import numpy as np
#a=[1,2,3,4,24,4,3,4]
arr=np.arange(1,23)
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [21]:
import numpy as np
#a=[1,2,3,4,24,4,3,4]
arr=np.arange(1,23)
arr[arr%2==0]


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [27]:
import numpy as np
#a=[1,2,3,4,24,4,3,4]
arr=np.arange(1,23)
arr[arr%2==0]=0
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0])

In [29]:
import numpy as np
#a=[1,2,3,4,24,4,3,4]
arr=np.arange(1,23)
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [43]:
import numpy as np
arr=np.arange(1,25)
arr[arr==10]

array([10])

In [51]:
import numpy as np
a=[]
size=int(input('enter your size of Array'))
for i in range(size):
    val=int(input('enter your value'))
    a.append(val)

arr=np.array(a)
arr[arr>2]

enter your size of Array 5
enter your value 1
enter your value 3
enter your value 2
enter your value 0
enter your value 9


array([3, 9])

In [53]:
import numpy as np
a=[]
size=int(input('enter your size of Array'))
for i in range(size):
    val=int(input('enter your value'))
    a.append(val)

arr=np.array(a)
arr[arr%2==0]

enter your size of Array 10
enter your value 2
enter your value 3
enter your value 1
enter your value 5
enter your value 6
enter your value 8
enter your value 10
enter your value 6
enter your value 12
enter your value 13


array([ 2,  6,  8, 10,  6, 12])

In [59]:
import numpy as np
a=[]
size=int(input('enter your size of Array'))
for i in range(size):
    val=int(input('enter your value'))
    a.append(val)

arr=np.array(a)

arr[arr>10]=0
print(arr)

enter your size of Array 5
enter your value 23
enter your value 45
enter your value 1
enter your value 2
enter your value 3


[0 0 1 2 3]
