In [1]:
import numpy as np
arr=np.zeros(2)
arr

array([0., 0.])

In [23]:
import numpy as np
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
import numpy as np
arr=np.eye((3))
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
import numpy as np
arr=np.eye((3))
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
import numpy as np
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
import numpy as np
arr=np.diag([1,2,3])
arr


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [31]:
import numpy as np
arr=np.diag([1,2,3])
arr
np.diag(arr)

array([1, 2, 3])

In [35]:
import numpy as np
arr=np.random.randint(1,100,1)
arr


array([26])

In [35]:
import numpy as np
arr=np.random.randint(1,100,1)
arr


array([26])

In [39]:
import numpy as np
arr=np.random.rand(3)
arr


array([0.47067066, 0.02253353, 0.1388537 ])

In [41]:
import numpy as np
arr=np.random.rand(2,3)
arr

array([[0.22154142, 0.31724785, 0.45897888],
       [0.538145  , 0.48816373, 0.26286285]])

In [49]:
import numpy as np
arr=np.random.randn(4)
arr

array([ 0.23485873, -0.90712229, -0.14122354,  1.25122746])