<h1>Creating Numpy Array</h1>

In [8]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [37]:
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [42]:
import numpy as np
c=np.array([[[1,2,3,4],[5,6,7,8],[9,10,2,32]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10  2 32]]]


In [49]:
import numpy as np
c=np.array([[[[1,2,3,4],[5,6,7,8],[9,10,2,32],[2,1,3,2]]]])
print(c)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10  2 32]
   [ 2  1  3  2]]]]


In [53]:
import numpy as np
np.array([[[1,2,3],[4,5,6]],[[12,3,1],[3,4,2]],[[13,4,5],[42,54,2]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12,  3,  1],
        [ 3,  4,  2]],

       [[13,  4,  5],
        [42, 54,  2]]])

<h1>Changing datatype in Array</h1>

In [15]:
import numpy as np 
a=np.array([1,2,3,4,5],dtype=float)
print(a)


[1. 2. 3. 4. 5.]


In [19]:
import numpy as np 
a=np.array([1,2,3,4,5],dtype=bool)
print(a)

[ True  True  True  True  True]


In [23]:
import numpy as np 
a=np.array([1,2,3,4,5],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


<h1>
    Different function in Numpy
</h1>

In [62]:
import numpy as np
a=np.arange(1,10,2)
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [85]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
import numpy as np
a=np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [89]:
import numpy as np
a=np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [91]:
import numpy as np
a=np.arange(1,13).reshape(2,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [95]:
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [103]:
import numpy as np
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [105]:
import numpy as np
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [115]:
import numpy as np
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [117]:
import numpy as np
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [119]:
import numpy as np
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<h1>Random function generate Numbers between 0 to 1</h1>

In [138]:
import numpy as np
a=np.random.random((3,3))
print(a)


[[0.34603187 0.59590908 0.35276502]
 [0.28363167 0.52392836 0.05011908]
 [0.45632641 0.41983075 0.01600947]]


<h1>Lin space generates number from given range also can generate from negta</h1>

In [134]:
import numpy as np
a=np.linspace(-10,10,6) # it will generate equal distance number
print(a)

[-10.  -6.  -2.   2.   6.  10.]


<h1>Array attributes</h1>

<H1>This is Shape Function that will tell array shape like 3 row 3 col pr 2 row,3 col</H1>

In [173]:
import numpy as np
a1=np.arange(10)
print(a1)
a1.shape


[0 1 2 3 4 5 6 7 8 9]


(10,)

In [179]:
import numpy as np
a2=np.arange(15).reshape(3,5)
print(a2)
a2.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [183]:
import numpy as np
a3=np.arange(16).reshape(2,2,2,2)
print(a3)
a3.shape

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


(2, 2, 2, 2)

<h1>ndim Tell about the dimension of array</h1>

In [186]:
import numpy as np
a1=np.arange(10)
print(a1)
a1.ndim

[0 1 2 3 4 5 6 7 8 9]


1

In [188]:
import numpy as np
a2=np.arange(15).reshape(3,5)
print(a2)
a2.ndim

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


2

In [190]:
import numpy as np
a3=np.arange(8).reshape(2,2,2)
print(a3)
a3.ndim

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


3

<h1>Size will tell us about size of array how many element are present in array</h1>

In [197]:
import numpy as np
b=np.arange(10)
print(b)
b.size

[0 1 2 3 4 5 6 7 8 9]


10

In [207]:
import numpy as np
b1=np.arange(12).reshape(3,4)
print(b1)
b1.size

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


12

<h1>Item size will tell how much size array have means how many byte it occupied</h1>

In [224]:
import numpy as np
c=np.arange(10,dtype =np.int32)
print(c)
c.itemsize

[0 1 2 3 4 5 6 7 8 9]


4

In [226]:
import numpy as np
c1=np.arange(12,dtype=np.int64).reshape(3,4)
print(c1)
c1.itemsize

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


8

<h1>
    dtype tell about datatype
</h1>

In [249]:
import numpy as np
d=np.arange(111111112)
print(d)
d.dtype

[        0         1         2 ... 111111109 111111110 111111111]


dtype('int32')

In [251]:
import numpy as np
d1=np.arange(12,dtype=float)
print(d1)
d1.dtype

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


dtype('float64')

<h1>Changing datatype</h1>

In [260]:
import numpy as np
d1=np.arange(12,dtype=np.int64).reshape(3,4)
print(d1)
d1.astype(np.int32)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h1>Mathematical Function in Numpy</h1>

<h1>max,min,sum,pro,dot</h1>

In [272]:
import numpy as np
f=np.arange(12).reshape(3,4)
print(f)
np.max(f)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


11

In [274]:
# for finding max in every row ,use axis=1,for col,use axis=0
np.max(f,axis=1)

array([ 3,  7, 11])

In [276]:
np.min(f)

0

In [278]:
np.min(f,axis=1)

array([0, 4, 8])

In [290]:
np.sum(f)

66

In [282]:
import numpy as np
f1=np.arange(12).reshape(3,4)
print(f1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [288]:
np.sum(f1)

66

In [292]:
np.sum(f1+f)

132

In [294]:
np.sum(f+f1,axis=1) # for finding sum of every row

array([12, 44, 76])

In [308]:
np.prod(f,axis=1)
np.prod(f,axis=0)

array([  0,  45, 120, 231])

In [312]:
import numpy as np
dot=np.arange(1,13).reshape(3,4)
print(dot)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [314]:
import numpy as np
dot1=np.arange(1,13).reshape(4,3)
print(dot1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [316]:
np.dot(dot,dot1)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

<h1>Mean, Median, Std, Var</h1>

In [3]:
import numpy as np
shah=np.arange(12).reshape(3,4)
print(shah)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
np.mean(shah)

5.5

In [7]:
np.mean(shah,axis=1)

array([1.5, 5.5, 9.5])

In [9]:
np.mean(shah,axis=0)

array([4., 5., 6., 7.])

In [13]:
np.median(shah)

5.5

In [15]:
np.median(shah,axis=1)

array([1.5, 5.5, 9.5])

In [17]:
np.std(shah)

3.452052529534663

In [19]:
np.var(shah)

11.916666666666666

In [21]:
np.var(shah,axis=1)

array([1.25, 1.25, 1.25])

<h1>Trigonometry Function</h1>

In [24]:
np.sin(shah)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [26]:
np.cos(shah)


array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

In [30]:
np.log(shah)

C:\Users\hamma\AppData\Local\Temp\ipykernel_12972\1574342300.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(shah)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [32]:
np.exp(shah)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

<h1>round floor ceil</h1>

In [43]:
import numpy as np
syed=np.random.random(10)*10
print(syed)
np.round(syed)

[3.67900607 2.61829733 9.67406266 9.90298949 4.06764446 6.52160768
 6.54589598 0.46386408 2.38931122 1.68599402]


array([ 4.,  3., 10., 10.,  4.,  7.,  7.,  0.,  2.,  2.])

In [45]:
np.floor(syed)

array([3., 2., 9., 9., 4., 6., 6., 0., 2., 1.])

In [47]:
np.ceil(syed)

array([ 4.,  3., 10., 10.,  5.,  7.,  7.,  1.,  3.,  2.])

<h1>Indexing and slicing</h1>

In [56]:
import numpy as np
sh=np.arange(12)
print(sh)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [62]:
sh[5]

5

In [66]:
import numpy as np
sh1=np.arange(12).reshape (3,4)
print(sh1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [90]:
sh1[1:3:2,2:3:2]

array([[6]])

In [92]:
sh1[1,2]

6

In [94]:
sh1[2,3]

11

In [100]:
sh1[2,0]

8

In [106]:
import numpy as np
sh2=np.arange(12).reshape(3,2,2)
print(sh2)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [108]:
sh2[0,1,1]

3

In [110]:
sh2[1,0,0:]

array([4, 5])

In [112]:
import numpy as np
sh3=np.arange(27).reshape(3,3,3)
print(sh3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [116]:
sh3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [118]:
sh3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
sh3[0,1,0::]

array([3, 4, 5])

In [124]:
sh3[0,1,0:]

array([3, 4, 5])

In [126]:
sh3[1,2,1]

16

In [132]:
sh3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [144]:
sh3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

<h1>Iteratig</h1>

In [149]:
for i in sh:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [153]:
for i in sh1:
    print(i)
    

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [155]:
for i in sh2:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 8  9]
 [10 11]]


In [173]:
for i in np.nditer(sh1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [161]:
sh1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [163]:
sh2.T

array([[[ 0,  4,  8],
        [ 2,  6, 10]],

       [[ 1,  5,  9],
        [ 3,  7, 11]]])

In [185]:
import numpy as np
hamm1=np.arange(12).reshape(3,4)
hamm2=np.arange(12).reshape(3,4)
np.hstack((hamm1,hamm2,hamm1))

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])

In [191]:
np.vstack((hamm1,hamm2,hamm1,hamm2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
for i in np.nditer(sh3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [179]:
np.ravel(sh3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [193]:
np.hsplit(hamm1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [195]:
np.vsplit(hamm2,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]