<h1>Numpy Tricks</h1>

<h1>Sorting</h1>

In [7]:
#sorting
import numpy as np
a=np.random.randint(1,100,10)
print(a)

[99 89 23 65 22 69  5 83 50 85]


In [9]:
np.sort(a)

array([ 5, 22, 23, 50, 65, 69, 83, 85, 89, 99])

In [19]:
#sorting
import numpy as np
a1=np.random.randint(1,100,10).reshape(2,5)
print(a1)

[[68 17 60  8 27]
 [47 25 73 17 78]]


In [27]:
np.sort(a1,axis=0)


array([[47, 17, 60,  8, 27],
       [68, 25, 73, 17, 78]])

In [25]:
np.sort(a1,axis=1)

array([[ 8, 17, 27, 60, 68],
       [17, 25, 47, 73, 78]])

<h1>Append</h1>

In [31]:
import numpy as np
b=np.arange(12)   #1D Array Example
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
np.append(b,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
import numpy as np
b1=np.arange(12).reshape(3,4)   #2D Array Example
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
np.append(b1,np.ones((b1.shape[0],1)),axis=1) # append in 2d arrays

array([[ 0.,  1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  7.,  1.],
       [ 8.,  9., 10., 11.,  1.]])

<h1>Concatenate</h1>

In [58]:
import numpy as np
c=np.random.randint(1,100,12).reshape(3,4)
print(c)

[[36 57 60 80]
 [ 2 71  8 61]
 [80 21 84 26]]


In [62]:
import numpy as np
d=np.random.randint(1,100,12).reshape(3,4)

In [66]:
np.concatenate((c,d),axis=1)

array([[36, 57, 60, 80, 30, 36, 75, 61],
       [ 2, 71,  8, 61, 32, 58, 95, 43],
       [80, 21, 84, 26, 88, 58, 76,  7]])

<h1>Unique</h1>

In [71]:
import numpy as np
u=np.array([1,1,1,1,1,2,2,2,2,3,3,33,3,3,4,4,4,5,4,5,6,7,87,6,7,7,9,9])
print(u)

[ 1  1  1  1  1  2  2  2  2  3  3 33  3  3  4  4  4  5  4  5  6  7 87  6
  7  7  9  9]


In [73]:
np.unique(u)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 33, 87])

<h1>converter row matrix and col matrix</h1>

In [78]:
import numpy as np
r=np.array([1,2,3,4,56])
print(r)

[ 1  2  3  4 56]


In [94]:
ha=np.expand_dims(r,axis=1).shape
print(ha)

(5, 1)


In [90]:
np.expand_dims(r,axis=0).shape



(1, 5)

<h1>Where IT gives index on a specific condition</h1>

In [99]:
import numpy as np
w=np.random.randint(1,100,15)
print(w)


[87 74 67 42 73 45 59 67 27 15 91 51 14 35 68]


In [105]:
n=np.where(w>50)
print(n)

(array([ 0,  1,  2,  4,  6,  7, 10, 11, 14], dtype=int64),)


In [107]:
np.where(w>50,0,w)

array([ 0,  0,  0, 42,  0, 45,  0,  0, 27, 15,  0,  0, 14, 35,  0])

In [109]:
np.where(w %1 ==0 ,0,w)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<h1>Find biggest NUmber index ,  argmax</h1>

In [112]:
np.argmax(w)

10

In [114]:
import numpy as np
b1=np.arange(12).reshape(3,4)   #2D Array Example
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [116]:
np.argmax(b1,axis=1)

array([3, 3, 3], dtype=int64)

In [118]:
np.argmax(b1,axis=0)

array([2, 2, 2, 2], dtype=int64)

<h1>Vice versa for minimumarg</h1>

In [129]:
import numpy as np
b=np.arange(12)   #1D Array Example
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [121]:
np.cumsum(b)


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [ ]:
import numpy as np
b=np.arange(12).reshape(3,4)   #1D Array Example
print(b)

In [125]:
np.cumsum(b,axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

<h1>Same as cumprod</h1>

<h1>Percentile</h1>

In [163]:
import numpy as np
b=np.array([1,2,3,4,5,6,7,8,9,10,11,12])   #1D Array Example
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [169]:
np.percentile(b,12)

2.32

<h1>histogram</h1>

In [151]:
import numpy as np
b=np.arange(101)   #1D Array Example
print(b)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [153]:
np.histogram(b,bins=[0,10,20,32,45,55,90,94,100])

(array([10, 10, 12, 13, 10, 35,  4,  7], dtype=int64),
 array([  0,  10,  20,  32,  45,  55,  90,  94, 100]))

<h1>correlation coficient
</h1>

In [158]:
import numpy as np
salary=np.array([200,300,400,500,600])
experience=np.array([1,2,3,4,5])
np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

<h1>isin   it will give same elemnt as output b/w two arrays</h1>

In [26]:
import numpy as np
si=np.array([1,2,3,4,5,6,7,8,9])
i=np.array([1,10,12,13,3,19,43])
si[np.isin(si,i)]

array([1, 3])

<h1>Flip function it will give mirror image </h1>

In [9]:
np.flip(si)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [13]:
import numpy as np
si1=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [15]:
np.flip(si1)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

<h1>Put value on a given index </h1>

In [42]:
import numpy as np
si=np.array([1,2,3,4,5,6,7,8,9])

In [46]:
 np.put(si,[1,3],[23,34])

In [48]:
np.delete(si,0)

array([23,  3, 34,  5,  6,  7,  8,  9])

<h1>Set function</h1>

In [53]:
import numpy as np
jk=np.array([1,2,5,3,0,34,6,7,87,10])

In [55]:
np.union1d(si,jk)

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 23, 34, 87])

In [57]:
np.intersect1d(si,jk)

array([ 1,  3,  5,  6,  7, 34])

In [59]:
np.setdiff1d(si,jk)

array([ 8,  9, 23])

In [63]:
np.setxor1d(si,jk)

array([ 0,  2,  8,  9, 10, 23, 87])

In [67]:
np.in1d(si,1)

array([ True, False, False, False, False, False, False, False, False])

In [69]:
np.clip(jk,a_min=10,a_max=88)

array([10, 10, 10, 10, 10, 34, 10, 10, 87, 10])