<h1>Converting 1D Array to 2D Array</h1>

In [21]:
import numpy as np
arr=np.random.randint(1,50,12)
arr.reshape  # this reshape keyword will reshape it 
arr=arr.reshape(3,4)  #it will tell how many row and column will bhi there
arr

array([[41,  8, 44, 20],
       [44, 37, 41,  1],
       [17, 38,  4, 19]])

In [29]:
import numpy as np
arr=np.random.randint(1,50,12)
arr.reshape  # this reshape keyword will reshape it 
arr=arr.reshape(3,4)  #it will tell how many row and column will bhi there
arr=arr.reshape(12)
arr

array([29, 47, 12, 41, 48,  3, 20, 38, 23, 37, 48, 19])

<h1>Number of dimension finding</h1>

In [32]:
import numpy as np
arr=np.random.randint(1,50,12)
arr.reshape  # this reshape keyword will reshape it 
arr=arr.reshape(3,4)  #it will tell how many row and column will bhi there
print('Number of dimension In  array',arr.ndim)

Number of dimension In  array 2


<h1>Changing rows and column</h1>

In [43]:
import numpy as np
arr=np.random.randint(1,50,12)
arr.reshape  # this reshape keyword will reshape it 
arr=arr.reshape(-1,4)  #it will tell how many row and column will bhi there
print('Array =',arr)
print('Number of dimension In  array',arr.ndim)

Array = [[32  8 15 17]
 [ 9 28 29  4]
 [20 12 36 36]]
Number of dimension In  array 2
