<h1>Generate Fix Number in using Seed Function</h1>

In [3]:
import numpy as np
np.random.seed(12)
arr=np.random.randint(1,100,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [7]:
import numpy as np
np.random.seed(12)
arr=np.random.randint(1,100,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [9]:
import numpy as np
np.random.seed(10)
arr=np.random.randint(1,100,10)
arr

array([10, 16, 65, 29, 90, 94, 30,  9, 74,  1])

In [11]:
import numpy as np
np.random.seed(12)
arr=np.random.randint(1,100,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [13]:
import numpy as np
np.random.seed(12)
arr=np.random.randint(1,100,10)
arr.size

10