<h1>Slicing and indexnig in two dimensional Arrays</h1>

In [13]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[5,6,7]])
arr

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [15]:
arr[0:3,0:2] # staring two o:3 tells about rows range and further will tell about col range

array([[1, 2],
       [2, 3],
       [5, 6]])

In [44]:
import numpy as np
np.random.seed(111)
arr=np.random.randint(1,500,30).reshape(6,5)
arr

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [42]:
import numpy as np
np.random.seed(111)
arr=np.random.randint(1,500,30)
arr1=arr.reshape(6,5)
arr1[3:5,2:]

array([[369, 217, 285],
       [ 22,  55, 201]])