<h1>Addition of Array<h1/>

In [4]:
import numpy as np
a=[]
size=int(input('Enter your Size'))
for i in range(size):
    val=int(input('Enter your value'))
    a.append(val)

arr=np.array(a)
print(arr+2)

Enter your Size 5
Enter your value 1
Enter your value 2
Enter your value 3
Enter your value 4
Enter your value 5


[3 4 5 6 7]


<h1>Multiplication</h1>

In [7]:
import numpy as np
a=[]
size=int(input('Enter your Size'))
for i in range(size):
    val=int(input('Enter your value'))
    a.append(val)

arr=np.array(a)
print(arr*2)

Enter your Size 5
Enter your value 2
Enter your value 1
Enter your value 4
Enter your value 3
Enter your value 7


[ 4  2  8  6 14]


<h1>Power</h1>

In [10]:
import numpy as np
a=[]
size=int(input('Enter your Size'))
for i in range(size):
    val=int(input('Enter your value'))
    a.append(val)

arr=np.array(a)
print(arr**2)

Enter your Size 5
Enter your value 1
Enter your value 2
Enter your value 3
Enter your value 4
Enter your value 5


[ 1  4  9 16 25]


<h1>Squareroot</h1>

In [24]:
import numpy as np
a=[]
size=int(input('Enter your Size'))
for i in range(size):
    val=int(input('Enter your value'))
    a.append(val)

arr=np.array(a)
print(arr**0.5)

Enter your Size 3
Enter your value 1
Enter your value 4
Enter your value 16


[1. 2. 4.]


<h1>Sum of Array</h1>

In [ ]:
import numpy as np
a=[]
size=int(input('Enter your Size of First Array :'))
for i in range(size):
    val=int(input('Enter your value in 1st Array'))
    a.append(val)

arr=np.array(a)

b=[]
size=int(input('Enter your Size of Second Array :'))
for i in range(size):
    value=int(input('Enter your value in 2nd Array '))
    b.append(value)

arr1=np.array(b)


print('sum of Array',arr+arr1)

<h1>Operation on 2D Arrays</h1>

In [35]:
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print(a+b)

[[2 4]
 [6 8]]


<h1>Addition of Two Matrix</h1>

In [37]:
import numpy as np

# Input first matrix
matrix = []
rows = int(input('Enter the Number of Rows for the first matrix: '))
col = int(input('Enter the Number of Columns for the first matrix: '))

for i in range(rows):
    a = []
    for j in range(col):
        val = int(input('Enter the Element in Matrix: '))
        a.append(val)
    matrix.append(a)

arr = np.array(matrix)
print("First Matrix:")
for i in range(rows):
    for j in range(col):
        print(arr[i][j], end=' ')
    print()

# Input second matrix
matrix1 = []
rows1 = int(input('Enter the Number of Rows for the second matrix: '))
col1 = int(input('Enter the Number of Columns for the second matrix: '))

for k in range(rows1):
    a1 = []
    for l in range(col1):
        val1 = int(input('Enter the Element in Matrix: '))
        a1.append(val1)
    matrix1.append(a1)

arr1 = np.array(matrix1)
print("Second Matrix:")
for k in range(rows1):
    for l in range(col1):
        print(arr1[k][l], end=' ')
    print()

# Add the two matrices
if rows == rows1 and col == col1:
    result = arr + arr1
    print("Resultant Matrix after Addition:")
    for i in range(rows):
        for j in range(col):
            print(result[i][j], end=' ')
        print()
else:
    print("Matrix addition is not possible. The dimensions do not match.")


Enter the Number of Rows for the first matrix:  2
Enter the Number of Columns for the first matrix:  2
Enter the Element in Matrix:  1
Enter the Element in Matrix:  2
Enter the Element in Matrix:  3
Enter the Element in Matrix:  4


First Matrix:
1 2 
3 4 


Enter the Number of Rows for the second matrix:  2
Enter the Number of Columns for the second matrix:  2
Enter the Element in Matrix:  1
Enter the Element in Matrix:  2
Enter the Element in Matrix:  3
Enter the Element in Matrix:  4


Second Matrix:
1 2 
3 4 
Resultant Matrix after Addition:
2 4 
6 8 


<h1>Multiplication of two matrix</h1>

In [43]:
import numpy as np

# Input first matrix
matrix = []
rows = int(input('Enter the Number of Rows for the first matrix: '))
col = int(input('Enter the Number of Columns for the first matrix: '))

for i in range(rows):
    a = []
    for j in range(col):
        val = int(input('Enter the Element in Matrix: '))
        a.append(val)
    matrix.append(a)

arr = np.array(matrix)
print("First Matrix:")
for i in range(rows):
    for j in range(col):
        print(arr[i][j], end=' ')
    print()

# Input second matrix
matrix1 = []
rows1 = int(input('Enter the Number of Rows for the second matrix: '))
col1 = int(input('Enter the Number of Columns for the second matrix: '))

for k in range(rows1):
    a1 = []
    for l in range(col1):
        val1 = int(input('Enter the Element in Matrix: '))
        a1.append(val1)
    matrix1.append(a1)

arr1 = np.array(matrix1)
print("Second Matrix:")
for k in range(rows1):
    for l in range(col1):
        print(arr1[k][l], end=' ')
    print()

# Multiplication of the two matrices
if col == rows1 :
    result = arr * arr1
    print("Resultant Matrix after Multipliaction:")
    for i in range(rows):
        for j in range(col):
            print(result[i][j], end=' ')
        print()
else:
    print("Matrix Multipliaction is not possible. The dimensions do not match.")

Enter the Number of Rows for the first matrix:  3
Enter the Number of Columns for the first matrix:  3
Enter the Element in Matrix:  1
Enter the Element in Matrix:  2
Enter the Element in Matrix:  3
Enter the Element in Matrix:  4
Enter the Element in Matrix:  5
Enter the Element in Matrix:  6
Enter the Element in Matrix:  7
Enter the Element in Matrix:  8
Enter the Element in Matrix:  9


First Matrix:
1 2 3 
4 5 6 
7 8 9 


Enter the Number of Rows for the second matrix:  3
Enter the Number of Columns for the second matrix:  3
Enter the Element in Matrix:  1
Enter the Element in Matrix:  2
Enter the Element in Matrix:  3
Enter the Element in Matrix:  4
Enter the Element in Matrix:  5
Enter the Element in Matrix:  6
Enter the Element in Matrix:  7
Enter the Element in Matrix:  8
Enter the Element in Matrix:  9


Second Matrix:
1 2 3 
4 5 6 
7 8 9 
Resultant Matrix after Multipliaction:
1 4 9 
16 25 36 
49 64 81 


<h1>Division of Matrix</h1>

In [48]:
import numpy as np

# Input first matrix
matrix = []
rows = int(input('Enter the Number of Rows for the first matrix: '))
col = int(input('Enter the Number of Columns for the first matrix: '))

for i in range(rows):
    a = []
    for j in range(col):
        val = int(input('Enter the Element in Matrix: '))
        a.append(val)
    matrix.append(a)

arr = np.array(matrix)
print("First Matrix:")
for i in range(rows):
    for j in range(col):
        print(arr[i][j], end=' ')
    print()

# Input second matrix
matrix1 = []
rows1 = int(input('Enter the Number of Rows for the second matrix: '))
col1 = int(input('Enter the Number of Columns for the second matrix: '))

for k in range(rows1):
    a1 = []
    for l in range(col1):
        val1 = int(input('Enter the Element in Matrix: '))
        a1.append(val1)
    matrix1.append(a1)

arr1 = np.array(matrix1)
print("Second Matrix:")
for k in range(rows1):
    for l in range(col1):
        print(arr1[k][l], end=' ')
    print()

# divide the two matrices
if rows == rows1 and col == col1:
    result = arr / arr1
    print("Resultant Matrix after Division:")
    for i in range(rows):
        for j in range(col):
            print(result[i][j], end=' ')
        print()
else:
    print("Matrix Divison is not possible. The dimensions do not match.")


Enter the Number of Rows for the first matrix:  2
Enter the Number of Columns for the first matrix:  2
Enter the Element in Matrix:  1
Enter the Element in Matrix:  2
Enter the Element in Matrix:  3
Enter the Element in Matrix:  4


First Matrix:
1 2 
3 4 


Enter the Number of Rows for the second matrix:  2
Enter the Number of Columns for the second matrix:  2
Enter the Element in Matrix:  1
Enter the Element in Matrix:  2
Enter the Element in Matrix:  3
Enter the Element in Matrix:  4


Second Matrix:
1 2 
3 4 
Resultant Matrix after Division:
1.0 1.0 
1.0 1.0 
