<h1>View Vs Copy</h1>

<h1>View</h1>

In [55]:
import numpy as np
a=np.array([1,2,3,4,5,67,5,4,356])
slicing=a[2:8]  # it will also updated original array
slicing[:]=0
a
#here original array is also change

array([  1,   2,   0,   0,   0,   0,   0,   0, 356])

<h1>Copy</h1>

In [40]:
import numpy as np
a=np.array([34,2,4,2,58,6,9,12])
slicing=a[2:7].copy()
slicing

array([ 4,  2, 58,  6,  9])

<h1>Copy</h1>

In [53]:
import numpy as np
a=np.array([34,2,4,2,58,6,9,12])
slicing=a[2:7].copy()
slicing[:]=0

a
#original array is same as before


array([34,  2,  4,  2, 58,  6,  9, 12])

In [11]:
import numpy as np
matrix=[]
row=int(input('enter your row size :'))
col=int(input('enter your col size :'))
for i in range(row):
    a=[]
    for j in range(col):
        element=int(input('enter your element'))
        a.append(element)
    matrix.append(a)
arr=np.array(matrix)
for i in range(row):
    for j in range(col):
        print(arr[i][j],end=' ')
    print()



    
        
        

enter your row size : 3
enter your col size : 3
enter your element 1
enter your element 2
enter your element 3
enter your element 4
enter your element 5
enter your element 6
enter your element 7
enter your element 8
enter your element 9


1 2 3 
4 5 6 
7 8 9 
